BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB
   gettext(u'Your shopping cart') 
BBBBBBBB

BBBBB BBBBBBB
  XXXX gettext(u'Your shopping cart') XXXXX
  XXXXXX XXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXX gettext(u'Image') XXXXX
        XXXX gettext(u'Product') XXXXX
        XXXX gettext(u'Quantity') XXXXX
        XXXX gettext(u'Remove') XXXXX
        XXXX gettext(u'Unit price') XXXXX
        XXXX gettext(u'Price') XXXXX
      XXXXX
    XXXXXXXX
    XXXXXXX
      BBB BBBB BB BBBB
        BBBB BBBBBBBBBBBBBBBBBBBB
          XXXX
            XXXX
              XX XXXXXXXX
                XXXX XXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
              XXXX
            XXXXX
            XXXXXXXXX
            XXXX
              XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXX
                
                
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBBBBBBBB
              XXXXXXX
            XXXXX
            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBXX gettext(u'Remove') XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX
          XXXXX
        BBBBBBB
      BBBBBB
      BB BBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXX
          XXXX gettext(u'Subtotal') XXXXX
          XXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXX
        XXXXX
        XXXX
           gettext(u'\n              <td>"%(code)s" coupon (%(discount)s%% off)</td>\n          ') 
              SSSSSSSSSSSSSS SSSSSS SSSSSSSSSSSSSSS SSSSSSSSS
          
          XXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXX XXXXX
            X XFFFFFFFFFFFFFFF
          XXXXX
        XXXXX
      BBBBB
      XXX XXXXXXXXXXXXXX
        XXXX gettext(u'Total') XXXXX
        XXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXX
          XFFFFFFFFFFFFFFF
        XXXXX
      XXXXX
    XXXXXXXX
  XXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX gettext(u'People who bought this also bought') XXXXX
      BBB B BB BBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX
          XX XXXXXXXX
            XXXX XXXXXBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
          XXXX
          XXXXX XXXXXXXXXXXXXXXX
        XXXXXX
      BBBBBB
    XXXXXX
  BBBBB
  XXX gettext(u'Apply a coupon') XXXXX
  XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
    
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Apply') XX
    BBBBBBBBBB
  XXXXXXX
  XX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXX gettext(u'Continue shopping') XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
       gettext(u'Checkout') 
    XXXX
  XXXX
BBBBBBBB