BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB

BBBBB BBBBBBBBBBBBB BBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX

    XXXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXX
      
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Add to cart') XX
    XXXXXXX

    FFFFFFFFFF
  XXXXXX
BBBBBBBB BBBBBBB