BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB

BBBBB BBBBB
  BB BBBBBBBBBBBB gettext(u'Products') BBBBB
BBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXX
    XXXX gettext(u'Categories') XXXXX
    XXXX
      XXX BB BBB BBBBBBBBXXXXXXXXXXXXXXXXBBBBBX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'All') XXXX
      XXXXX
      BBB B BB BBBBBBBBBB
        XXX BB BBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXBBBBBX
          XX XXXXXXXXXXXX
        XXXXX
      BBBBBB
    XXXXX
  XXXXXX
  XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXBB BBBBBBBBBBBB gettext(u'Products') BBBBBXXXXX
    BBB BBBBBBB BB BBBBBBBB
      XXXX XXXXXXXXXXXXX
        XX XXXXXXXX
          XXXX XXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
        XXXX
        XX XXXXXXXXXXXXXXXX
        X
      XXXXXX
    BBBBBB
  XXXXXX
BBBBBBBB