BBBB BBBB
BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXXXXBBBBB BBBBB gettext(u'My shop') BBBBBBBB BBBBBXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
XXXXXXX
XXXXXX
  XXXX XXXXXXXXXXXX
    XX XXXXXXXX XXXXXXXXXXXXX gettext(u'My shop') XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX
        XXXXXX XXXXX XXXX XXX XXXX XXXXXXX XXXXXXXXX XXXXX XXXXXXX XXX XXXXXXXX XXXX
        XXXXXXXXXX XXXX XXX XXXXXXX XXXXXXXX  XXXX XXXX XX XXXXXXX XX XXX XXXX XXXXX
        XX XXXXXXXX  XXXXXXXXXXX XX X XXXXXXXX XXXXXXXX XXXX XX XXXXXXX XXXXX XXX XXXXXX
        XXXXXXXXXX  XXXXXXXXXXXXXXXXX XX X XXXXXX XXXX XXX XXXX XXXXXX
      XXX
      BBBB BBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBB B B
           gettext(u'Your cart') X
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX
             gettext(u'\n              %(total_items)s item%(total_items_plural)s,\n              $%(total_price)s\n            ') 
              SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSS
              SSSSSSSSSSSSSSSS
            
          XXXX
        BBBB
          gettext(u'Your cart is empty.') 
        BBBBB
      BBBBBBB
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXX
    BBBBB BBBBBBB
    BBBBBBBB BBBBBBB
  XXXXXX
XXXXXXX
XXXXXXX